#!/usr/bin/env bash
# validate-commit.sh — Pre-commit validation hook.
# Hook: PreToolUse (matcher: Bash)
# Checks staged files for secrets, JSON validity, commit format.
# Exit 0 = pass (with warnings), Exit 2 = block.

# Only run on git commit commands
INPUT=$(cat 2>/dev/null || true)
COMMAND=""
if command -v jq &>/dev/null; then
  COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null || true)
else
  COMMAND=$(echo "$INPUT" | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*: *"//;s/"$//' || true)
fi

# Only validate git commit commands
case "$COMMAND" in
  *"git commit"*) ;;
  *) exit 0 ;;
esac

WARNINGS=0
BLOCKS=0

# Check for hardcoded secrets in staged files
STAGED=$(git diff --cached --name-only 2>/dev/null || true)
if [ -n "$STAGED" ]; then
  # Prefer dedicated secret scanners if available (more accurate, fewer false positives)
  if command -v gitleaks &>/dev/null; then
    SECRETS_FOUND=$(gitleaks detect --staged --no-banner 2>&1 || true)
    if echo "$SECRETS_FOUND" | grep -qiE 'leaks? found|secret|token'; then
      echo "BLOCK: gitleaks detected secrets in staged changes:"
      echo "$SECRETS_FOUND" | head -5
      BLOCKS=$((BLOCKS + 1))
    fi
  elif command -v trufflehog &>/dev/null; then
    SECRETS_FOUND=$(trufflehog git --staged --no-update --only-verified 2>&1 || true)
    if [ -n "$SECRETS_FOUND" ]; then
      echo "BLOCK: trufflehog detected secrets in staged changes:"
      echo "$SECRETS_FOUND" | head -5
      BLOCKS=$((BLOCKS + 1))
    fi
  else
    # Fallback: regex-based detection (catches obvious patterns)
    SECRETS_FOUND=$(git diff --cached -U0 2>/dev/null | grep -iE '^\+.*(sk-[a-zA-Z0-9]{20,}|AKIA[A-Z0-9]{16}|password\s*=\s*["\x27][^"\x27]+|api_key\s*=\s*["\x27][^"\x27]+|secret\s*=\s*["\x27][^"\x27]+)' | head -5 || true)
    if [ -n "$SECRETS_FOUND" ]; then
      echo "BLOCK: Potential secrets detected in staged changes:"
      echo "$SECRETS_FOUND" | head -3
      echo "Remove secrets and use environment variables instead."
      echo "(Install gitleaks for better detection: brew install gitleaks)"
      BLOCKS=$((BLOCKS + 1))
    fi
  fi

  # Validate JSON files
  for file in $STAGED; do
    if [[ "$file" == *.json ]] && [ -f "$file" ]; then
      if command -v node &>/dev/null; then
        if ! node -e "JSON.parse(require('fs').readFileSync('$file','utf-8'))" 2>/dev/null; then
          echo "BLOCK: Invalid JSON in $file"
          BLOCKS=$((BLOCKS + 1))
        fi
      fi
    fi
  done

  # Check for TODO without assignee
  BARE_TODOS=$(git diff --cached -U0 2>/dev/null | grep -E '^\+.*TODO[^(]' | head -3 || true)
  if [ -n "$BARE_TODOS" ]; then
    echo "WARNING: TODOs without assignee found. Use TODO(name) format."
    WARNINGS=$((WARNINGS + 1))
  fi

  # Conventional commit format check (warn, don't block — commit message may not be final)
  # mesh(task-id) prefix is exempt (auto-generated by mesh-agent)
  COMMIT_MSG=$(echo "$COMMAND" | grep -oP '(?<=-m\s")[^"]*|(?<=-m\s'"'"')[^'"'"']*' 2>/dev/null || true)
  if [ -n "$COMMIT_MSG" ]; then
    if ! echo "$COMMIT_MSG" | grep -qE '^(feat|fix|docs|style|refactor|test|chore|build|ci|perf|revert|mesh)(\(.+\))?: .+'; then
      echo "WARNING: Commit message doesn't follow conventional format: type(scope): description"
      WARNINGS=$((WARNINGS + 1))
    fi
  fi
fi

if [ $BLOCKS -gt 0 ]; then
  echo ""
  echo "Commit blocked: $BLOCKS issue(s) must be fixed."
  exit 2
fi

if [ $WARNINGS -gt 0 ]; then
  echo ""
  echo "Commit allowed with $WARNINGS warning(s)."
fi

exit 0
