#!/usr/bin/env bash
# memory-plan-timeline.sh — regenerate memory-plan/TIMELINE.md from the plan state.
#
# Idempotent — rewrites the file in full each invocation. Safe to run any time.
# Called by the tick wrapper after each tick (closed or blocked). Can be run
# manually any time: `./workspace-bin/memory-plan-timeline.sh`
#
# Sources:
#   - git log (the canonical step-close history; one commit per closed step)
#   - memory-plan/INVENTORY.md (queued / in-flight rows)
#   - memory-plan/VERSION (current carrier)
#   - memory-plan/BLOCKED.md (if present)
#   - memory-plan/audits/*/AUDIT_POST.md (V2 findings counts)
#   - memory-plan/tick-logs/*.log (most recent tick metadata)

set -u

REPO="/Users/moltymac/openclaw-nodedev"
PLAN="${REPO}/memory-plan"
OUT="${PLAN}/TIMELINE.md"

cd "${REPO}"

# Headline counts (reuse the same logic as memory-plan-status.sh).
CLOSED=$(grep -E '^\| [0-9]+ \| [0-9]+\.[0-9]+ \| v[0-9]+\.[0-9]+ \| \[x\]' "${PLAN}/INVENTORY.md" 2>/dev/null | wc -l | tr -d ' ')
ACTIVE=$(grep -E '^\| [0-9]+ \| [0-9]+\.[0-9]+ \| v[0-9]+\.[0-9]+ \| \[A\]' "${PLAN}/INVENTORY.md" 2>/dev/null | wc -l | tr -d ' ')
TOTAL=$(grep -E '^\| [0-9]+ \| [0-9]+\.[0-9]+' "${PLAN}/INVENTORY.md" 2>/dev/null | wc -l | tr -d ' ')
VERSION=$(cat "${PLAN}/VERSION" 2>/dev/null || echo "<missing>")
BLOCKED=$([ -f "${PLAN}/BLOCKED.md" ] && echo "yes" || echo "no")

# Write the file.
{
  printf '# OpenClaw Memory Plan — Timeline\n\n'
  printf 'Auto-regenerated by `workspace-bin/memory-plan-timeline.sh` after each tick.\n'
  printf 'Read-only artifact — edits will be overwritten. Source of truth is git log + audits/.\n\n'
  printf '_Last refresh: %s_\n\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')"

  printf '## Status\n\n'
  printf '| Field | Value |\n|---|---|\n'
  printf '| Version carrier | `%s` |\n' "${VERSION}"
  printf '| Closed steps | %s / %s |\n' "${CLOSED}" "${TOTAL}"
  printf '| In-flight | %s |\n' "${ACTIVE}"
  printf '| Blocked | %s |\n' "${BLOCKED}"
  if [ "${BLOCKED}" = "yes" ]; then
    TRIG=$(grep -m1 '^\*\*Trigger\*\*:' "${PLAN}/BLOCKED.md" 2>/dev/null | sed 's/^\*\*Trigger\*\*: //')
    printf '| Block reason | %s |\n' "${TRIG:-see BLOCKED.md}"
  fi
  printf '\n'

  # Closed steps — one row per v0.x/v1.x/... commit in chronological order.
  printf '## Closed steps\n\n'
  printf '| When | Version | Step | V2 + / 8-patches | Commit |\n'
  printf '|---|---|---|---|---|\n'

  # Iterate commits matching ^v\d+\.\d+ in subject (oldest first for readability).
  git log --reverse --format='%h%x09%ai%x09%s' --grep='^v[0-9]\+\.[0-9]\+ ' 2>/dev/null | while IFS=$'\t' read -r HASH ISO SUBJ; do
    # Parse the version + step description out of the subject.
    VER=$(printf '%s' "${SUBJ}" | sed -E 's/^(v[0-9]+\.[0-9]+) .*/\1/')
    DESC=$(printf '%s' "${SUBJ}" | sed -E 's/^v[0-9]+\.[0-9]+ — //')
    DATE=$(printf '%s' "${ISO}" | cut -c1-16)

    # Look up audit-post for V2 / 8-patch counts.
    BLOCK_NUM=$(printf '%s' "${VER}" | sed -E 's/^v([0-9]+)\.[0-9]+/\1/')
    STEP_NUM=$(printf '%s' "${VER}" | sed -E 's/^v[0-9]+\.([0-9]+)/\1/')
    # Step folder names are zero-padded (step01, step02, ...). The headless tick
    # numbers them by global step index, not block.step — so use the file system.
    AUDIT_DIR=$(ls -d "${PLAN}/audits/step"*"_"* 2>/dev/null | grep -E "/step0*$(( (BLOCK_NUM * 7 / 7) + 1 ))_" 2>/dev/null | head -1 || true)
    # Fallback: pattern-match by global step number derived from CLOSED counter.
    # Simpler: parse all audit dirs and link by AUDIT_POST mention of the version.
    POST_FILE=$(grep -lE "\*\*Version:\*\* ${VER}-mid" "${PLAN}/audits/"step*/AUDIT_POST.md 2>/dev/null | head -1 || true)

    if [ -n "${POST_FILE}" ]; then
      POS=$(grep -E '^- \[POSITIVE\]' "${POST_FILE}" 2>/dev/null | wc -l | tr -d ' ')
      NEG=$(grep -E '^- \[NEGATIVE\]' "${POST_FILE}" 2>/dev/null | wc -l | tr -d ' ')
      # Phase 8 patches: count §5 entries that are not "None"
      PATCHES=$(awk '/^## §5/,/^## §6/' "${POST_FILE}" 2>/dev/null | grep -E '^[*-] ' | wc -l | tr -d ' ')
      AUDIT_REL=$(printf '%s' "${POST_FILE}" | sed "s|^${REPO}/||")
      AUDIT_LINK="[+${POS}/-${NEG}, ${PATCHES} patches](${AUDIT_REL})"
    else
      AUDIT_LINK="—"
    fi

    printf '| %s | `%s` | %s | %s | `%s` |\n' "${DATE}" "${VER}" "${DESC}" "${AUDIT_LINK}" "${HASH}"
  done
  printf '\n'

  # In-flight (current step, if any).
  printf '## In-flight\n\n'
  IN_FLIGHT_ROW=$(grep -E '^\| [0-9]+ \| [0-9]+\.[0-9]+ \| v[0-9]+\.[0-9]+ \| \[A\]' "${PLAN}/INVENTORY.md" 2>/dev/null | head -1 || true)
  if [ -n "${IN_FLIGHT_ROW}" ]; then
    printf '%s\n\n' "${IN_FLIGHT_ROW}"
    printf 'Current version carrier: `%s`\n\n' "${VERSION}"
  else
    printf '_(no step in flight)_\n\n'
  fi

  # Queue (first 5 queued).
  printf '## Queue (next 5)\n\n'
  printf '| Step | Version | Description |\n|---|---|---|\n'
  grep -E '^\| [0-9]+ \| [0-9]+\.[0-9]+ \| v[0-9]+\.[0-9]+ \| \[ \]' "${PLAN}/INVENTORY.md" 2>/dev/null | head -5 | sed -E 's/^\| ([0-9]+) \| ([0-9]+\.[0-9]+) \| (v[0-9]+\.[0-9]+) \| \[ \] \| (.+) \|$/| \2 | `\3` | \4 |/' || true
  printf '\n'

  # Recent ticks (last 10).
  printf '## Recent ticks (last 10 wrapper invocations)\n\n'
  printf '| When | Log | Bytes |\n|---|---|---|\n'
  ls -1t "${PLAN}/tick-logs/"*.log 2>/dev/null | head -10 | while read -r LOG; do
    [ -z "${LOG}" ] && continue
    NAME=$(basename "${LOG}")
    SIZE=$(stat -f '%z' "${LOG}" 2>/dev/null || echo 0)
    MTIME=$(stat -f '%Sm' -t '%Y-%m-%d %H:%M' "${LOG}" 2>/dev/null || echo '?')
    printf '| %s | `%s` | %s |\n' "${MTIME}" "${NAME}" "${SIZE}"
  done
} > "${OUT}"

exit 0
